# A pod with all transparency information specified
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-information
  labels:
    app: pod-with-information
  annotations:
    autoDecision: "false"
    necessity: "Meeting pre - contractual and contractual obligations to users without which they cannot use the service"
    dataCategories: "[{\"name\":\"name\",\"purpose\":\"Mandatory information to send packages\",\"legalBasis\":\"SGB-100-42\",\"storage\":\"Until closing of account\"},{\"name\":\"address\",\"purpose\":\"Mandatory information to send packages\",\"legalBasis\":\"SGB-100-42\",\"storage\":\"Until closing of account\"}]"
spec:
  restartPolicy: OnFailure
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "echo I am running as user $(id -u)"]
