# A pod with all transparency information specified
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-information
  labels:
    app: pod-with-information
  annotations:
    purposes: given
    dataCategories: given
spec:
  restartPolicy: OnFailure
  containers:
  - name: busybox
    image: busybox
    command: ["sh", "-c", "echo I am running as user $(id -u)"]
